### ISSUE TITLE
Assignment 2 ready to grade

### ISSUE THREAD

**Issue by ryan6351** [SES-5215-F2020/rjohnson-quant#2]
Hey y'all,

My submission for assignment 2 is ready to be graded! This one was a bit more challenging, especially correcting several errors in my categorical variable charts and tables.

Thanks!

https://ses-5215-f2020.github.io/rjohnson-quant/Assignment2.html

**Comment by c-voulgaris** [comment]
Great work!

**Lines 160, 164, 168, and 169:** For the household size calculations, especially the average, confidence interval, and standard deviation, it would be helpful to show one or two digits after the decimal point. The median and interquartile range are likely to by whole numbers, so just showing the result as an integer is fine there.

**Line 225-226:** Likewise for the 95-percent confidence interval for number of bedrooms - showing one more digit after the decimal would probably clarify that there is some variation with that range.

**Lines 227 and 338:** results='hide' here means that the tables you're creating with knittr::kable aren't displayed. 

**Line 236:** The reason you have gaps in your histogram is because your binwidth is set to 0.5. So every second bin on the histogram is empty because those represent the number of values with 1.5, 2.5, 3.5, etc bedrooms.

**Throughout:** You have a "* " at the beginning of each line of Markdown text (i.e. the text between the code chunks). This creates a bullet point. Was this your intention? You can delete all those asterisks if what you want is just regular text.
